=== nunocaseiro/picking-warehouse-javafx/src/warehouseSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "id": "http://example.com/example.json",
  "type": "object",
  "title": "The root schema",
  "description": "The root schema comprises the entire JSON document.",
  "default": {},
  "examples": [
    {
      "nodes": [
        {
          "line": 0,
          "nodeNumber": 1,
          "column": 1,
          "successors": [
            {
              "distance": 8.0,
              "nodeNumber": 2
            },
            {
              "distance": 3.0,
              "nodeNumber": 6
            }
          ],
          "type": "D"
        }
      ],
      "edges": [
        {
          "distance": 3,
          "node1Number": 1,
          "edgeNumber": 1,
          "node2Number": 6,
          "direction": 1
        }
      ],
      "agents": [
        {
          "line": 12,
          "column": 4,
          "edgeNumber": 13,
          "capacity": 75
        }
      ],
      "offloadArea": 36,
      "maxLine": 32,
      "maxColumn": 20
    }
  ],
  "required": [
    "nodes",
    "edges",
    "agents",
    "offloadArea",
    "maxLine",
    "maxColumn"
  ],
  "additionalProperties": true,
  "properties": {
    "nodes": {
      "id": "#/properties/nodes",
      "type": "array",
      "title": "The nodes schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "examples": [
        [
          {
            "line": 0,
            "nodeNumber": 1,
            "column": 1,
            "successors": [
              {
                "distance": 8.0,
                "nodeNumber": 2
              },
              {
                "distance": 3.0,
                "nodeNumber": 6
              }
            ],
            "type": "D"
          }
        ]
      ],
      "additionalItems": true,
      "items": {
        "anyOf": [
          {
            "id": "#/properties/nodes/items/anyOf/0",
            "type": "object",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [
              {
                "line": 0,
                "nodeNumber": 1,
                "column": 1,
                "successors": [
                  {
                    "distance": 8.0,
                    "nodeNumber": 2
                  },
                  {
                    "distance": 3.0,
                    "nodeNumber": 6
                  }
                ],
                "type": "D"
              }
            ],
            "required": [
              "line",
              "nodeNumber",
              "column",
              "successors",
              "type"
            ],
            "additionalProperties": true,
            "properties": {
              "line": {
                "id": "#/properties/nodes/items/anyOf/0/properties/line",
                "type": "integer",
                "title": "The line schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  0
                ]
              },
              "nodeNumber": {
                "id": "#/properties/nodes/items/anyOf/0/properties/nodeNumber",
                "type": "integer",
                "title": "The nodeNumber schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  1
                ]
              },
              "column": {
                "id": "#/properties/nodes/items/anyOf/0/properties/column",
                "type": "integer",
                "title": "The column schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  1
                ]
              },
              "successors": {
                "id": "#/properties/nodes/items/anyOf/0/properties/successors",
                "type": "array",
                "title": "The successors schema",
                "description": "An explanation about the purpose of this instance.",
                "default": [],
                "examples": [
                  [
                    {
                      "distance": 8.0,
                      "nodeNumber": 2
                    },
                    {
                      "distance": 3.0,
                      "nodeNumber": 6
                    }
                  ]
                ],
                "additionalItems": true,
                "items": {
                  "anyOf": [
                    {
                      "id": "#/properties/nodes/items/anyOf/0/properties/successors/items/anyOf/0",
                      "type": "object",
                      "title": "The first anyOf schema",
                      "description": "An explanation about the purpose of this instance.",
                      "default": {},
                      "examples": [
                        {
                          "distance": 8.0,
                          "nodeNumber": 2
                        }
                      ],
                      "required": [
                        "distance",
                        "nodeNumber"
                      ],
                      "additionalProperties": true,
                      "properties": {
                        "distance": {
                          "id": "#/properties/nodes/items/anyOf/0/properties/successors/items/anyOf/0/properties/distance",
                          "type": "number",
                          "title": "The distance schema",
                          "description": "An explanation about the purpose of this instance.",
                          "default": 0.0,
                          "examples": [
                            8.0
                          ]
                        },
                        "nodeNumber": {
                          "id": "#/properties/nodes/items/anyOf/0/properties/successors/items/anyOf/0/properties/nodeNumber",
                          "type": "integer",
                          "title": "The nodeNumber schema",
                          "description": "An explanation about the purpose of this instance.",
                          "default": 0,
                          "examples": [
                            2
                          ]
                        }
                      }
                    }
                  ],
                  "id": "#/properties/nodes/items/anyOf/0/properties/successors/items"
                }
              },
              "type": {
                "id": "#/properties/nodes/items/anyOf/0/properties/type",
                "type": "string",
                "title": "The type schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                  "D"
                ]
              }
            }
          }
        ],
        "id": "#/properties/nodes/items"
      }
    },
    "edges": {
      "id": "#/properties/edges",
      "type": "array",
      "title": "The edges schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "examples": [
        [
          {
            "distance": 3,
            "node1Number": 1,
            "edgeNumber": 1,
            "node2Number": 6,
            "direction": 1
          }
        ]
      ],
      "additionalItems": true,
      "items": {
        "anyOf": [
          {
            "id": "#/properties/edges/items/anyOf/0",
            "type": "object",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [
              {
                "distance": 3,
                "node1Number": 1,
                "edgeNumber": 1,
                "node2Number": 6,
                "direction": 1
              }
            ],
            "required": [
              "distance",
              "node1Number",
              "edgeNumber",
              "node2Number",
              "direction"
            ],
            "additionalProperties": true,
            "properties": {
              "distance": {
                "id": "#/properties/edges/items/anyOf/0/properties/distance",
                "type": "integer",
                "title": "The distance schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  3
                ]
              },
              "node1Number": {
                "id": "#/properties/edges/items/anyOf/0/properties/node1Number",
                "type": "integer",
                "title": "The node1Number schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  1
                ]
              },
              "edgeNumber": {
                "id": "#/properties/edges/items/anyOf/0/properties/edgeNumber",
                "type": "integer",
                "title": "The edgeNumber schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  1
                ]
              },
              "node2Number": {
                "id": "#/properties/edges/items/anyOf/0/properties/node2Number",
                "type": "integer",
                "title": "The node2Number schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  6
                ]
              },
              "direction": {
                "id": "#/properties/edges/items/anyOf/0/properties/direction",
                "type": "integer",
                "title": "The direction schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  1
                ]
              }
            }
          }
        ],
        "id": "#/properties/edges/items"
      }
    },
    "agents": {
      "id": "#/properties/agents",
      "type": "array",
      "title": "The agents schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "examples": [
        [
          {
            "line": 12,
            "column": 4,
            "edgeNumber": 13,
            "capacity": 75
          }
        ]
      ],
      "additionalItems": true,
      "items": {
        "anyOf": [
          {
            "id": "#/properties/agents/items/anyOf/0",
            "type": "object",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [
              {
                "line": 12,
                "column": 4,
                "edgeNumber": 13,
                "capacity": 75
              }
            ],
            "required": [
              "line",
              "column",
              "edgeNumber",
              "capacity"
            ],
            "additionalProperties": true,
            "properties": {
              "line": {
                "id": "#/properties/agents/items/anyOf/0/properties/line",
                "type": "integer",
                "title": "The line schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  12
                ]
              },
              "column": {
                "id": "#/properties/agents/items/anyOf/0/properties/column",
                "type": "integer",
                "title": "The column schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  4
                ]
              },
              "edgeNumber": {
                "id": "#/properties/agents/items/anyOf/0/properties/edgeNumber",
                "type": "integer",
                "title": "The edgeNumber schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  13
                ]
              },
              "capacity": {
                "id": "#/properties/agents/items/anyOf/0/properties/capacity",
                "type": "integer",
                "title": "The capacity schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  75
                ]
              }
            }
          }
        ],
        "id": "#/properties/agents/items"
      }
    },
    "offloadArea": {
      "id": "#/properties/offloadArea",
      "type": "integer",
      "title": "The offloadArea schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [
        36
      ]
    },
    "maxLine": {
      "id": "#/properties/maxLine",
      "type": "integer",
      "title": "The maxLine schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [
        32
      ]
    },
    "maxColumn": {
      "id": "#/properties/maxColumn",
      "type": "integer",
      "title": "The maxColumn schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [
        20
      ]
    }
  }
}

=== nunocaseiro/picking-warehouse-javafx/src/WarehouseLayout.json
{
    "nodes": [
        {
            "line": 0,
            "nodeNumber": 1,
            "column": 1,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 2
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 6
                }
            ],
            "type": "D"
        },
        {
            "line": 8,
            "nodeNumber": 2,
            "column": 1,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 1
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 7
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 3
                }
            ],
            "type": "D"
        },
        {
            "line": 16,
            "nodeNumber": 3,
            "column": 1,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 2
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 8
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 4
                }
            ],
            "type": "D"
        },
        {
            "line": 24,
            "nodeNumber": 4,
            "column": 1,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 3
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 9
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 5
                }
            ],
            "type": "D"
        },
        {
            "line": 32,
            "nodeNumber": 5,
            "column": 1,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 4
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 10
                }
            ],
            "type": "D"
        },
        {
            "line": 0,
            "nodeNumber": 6,
            "column": 4,
            "successors": [
                {
                    "distance": 3.0,
                    "nodeNumber": 1
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 7
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 11
                }
            ],
            "type": "D"
        },
        {
            "line": 8,
            "nodeNumber": 7,
            "column": 4,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 6
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 12
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 2
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 8
                }
            ],
            "type": "D"
        },
        {
            "line": 16,
            "nodeNumber": 8,
            "column": 4,
            "successors": [
                {
                    "distance": 3.0,
                    "nodeNumber": 13
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 9
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 3
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 7
                }
            ],
            "type": "D"
        },
        {
            "line": 24,
            "nodeNumber": 9,
            "column": 4,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 8
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 14
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 10
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 4
                }
            ],
            "type": "D"
        },
        {
            "line": 32,
            "nodeNumber": 10,
            "column": 4,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 9
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 15
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 5
                }
            ],
            "type": "D"
        },
        {
            "line": 0,
            "nodeNumber": 11,
            "column": 7,
            "successors": [
                {
                    "distance": 3.0,
                    "nodeNumber": 6
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 16
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 12
                }
            ],
            "type": "D"
        },
        {
            "line": 8,
            "nodeNumber": 12,
            "column": 7,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 11
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 17
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 13
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 7
                }
            ],
            "type": "D"
        },
        {
            "line": 16,
            "nodeNumber": 13,
            "column": 7,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 12
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 18
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 8
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 14
                }
            ],
            "type": "D"
        },
        {
            "line": 24,
            "nodeNumber": 14,
            "column": 7,
            "successors": [
                {
                    "distance": 3.0,
                    "nodeNumber": 19
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 15
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 9
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 13
                }
            ],
            "type": "D"
        },
        {
            "line": 32,
            "nodeNumber": 15,
            "column": 7,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 14
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 20
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 10
                }
            ],
            "type": "D"
        },
        {
            "line": 0,
            "nodeNumber": 16,
            "column": 10,
            "successors": [
                {
                    "distance": 3.0,
                    "nodeNumber": 11
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 21
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 17
                }
            ],
            "type": "D"
        },
        {
            "line": 8,
            "nodeNumber": 17,
            "column": 10,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 16
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 22
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 18
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 12
                }
            ],
            "type": "D"
        },
        {
            "line": 16,
            "nodeNumber": 18,
            "column": 10,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 17
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 23
                },
                {
                    "distance": 8.0,
                    "nodeNumber": 19
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 13
                }
            ],
            "type": "D"
        },
        {
            "line": 24,
            "nodeNumber": 19,
            "column": 10,
            "successors": [
                {
                    "distance": 8.0,
                    "nodeNumber": 18
                },
                {
                    "distance": 3.0,
                    "nodeNumber": 24
                },
                {
